data = ("Adil" , "Faisal" , "Abubakar" , "Shakin" , "Obaid")
print("The man",data[0], "Should rule the world :)")
print("The man",data[1], "Should rule the world :)")
print("The man",data[2], "Should rule the world :)")
print("The man",data[3], "Should rule the world :)")
print("The man",data[4], "Should rule the world :)")